package com.teamdelta.sandwichpitstop.dm;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "order", catalog = "sandwich_pit_stop")
@SuppressWarnings("serial")
public class Order implements java.io.Serializable {

	private int orderId;
	private Date placedTimestamp;
	private Date completeTimestamp;
	private String customerName;
	private Set<Sandwich> sandwiches = new HashSet<Sandwich>(0);

	public Order() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "order_id", unique = true, nullable = false)
	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "placed_timestamp", nullable = false, length = 19)
	public Date getPlacedTimestamp() {
		return this.placedTimestamp;
	}

	public void setPlacedTimestamp(Date placedTimestamp) {
		this.placedTimestamp = placedTimestamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "complete_timestamp", length = 19)
	public Date getCompleteTimestamp() {
		return this.completeTimestamp;
	}

	public void setCompleteTimestamp(Date completeTimestamp) {
		this.completeTimestamp = completeTimestamp;
	}

	@Column(name = "customer_name", nullable = false, length = 45)
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "order")
	public Set<Sandwich> getSandwiches() {
		return this.sandwiches;
	}

	public void setSandwiches(Set<Sandwich> sandwiches) {
		this.sandwiches = sandwiches;
	}

}
