-- MySQL Script generated by MySQL Workbench
-- 07/29/17 18:44:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `type` VARCHAR(2) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `order` ;

CREATE TABLE IF NOT EXISTS `order` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `placed_timestamp` DATETIME NOT NULL,
  `complete_timestamp` DATETIME NULL,
  `customer_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`order_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sandwich`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sandwich` ;

CREATE TABLE IF NOT EXISTS `sandwich` (
  `sandwich_id` INT NOT NULL AUTO_INCREMENT,
  `bread` VARCHAR(2) NOT NULL,
  `substance` VARCHAR(2) NOT NULL,
  `cheese` VARCHAR(2) NOT NULL,
  `tomatos` TINYINT(1) NOT NULL,
  `lettuce` TINYINT(1) NOT NULL,
  `dressing` VARCHAR(2) NOT NULL,
  `onions` TINYINT(1) NOT NULL,
  `comments` VARCHAR(250) NULL,
  `order_id` INT NOT NULL,
  `status` VARCHAR(2) NOT NULL,
  `placed_timestamp` DATETIME NOT NULL,
  `complete_timestamp` DATETIME NULL,
  `preparer_id` INT NULL,
  `price` DOUBLE NOT NULL,
  PRIMARY KEY (`sandwich_id`),
  INDEX `fk_sandwich_order_idx` (`order_id` ASC),
  INDEX `fk_sandwich_user1_idx` (`preparer_id` ASC),
  CONSTRAINT `fk_sandwich_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `order` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sandwich_user1`
    FOREIGN KEY (`preparer_id`)
    REFERENCES `user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
